version: "3"
services:
  db:
    image: postgres
    container_name: wallet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/data:/var/lib/postgres:rw
    ports:
      - "5432:5432"
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always


