spring:
  profiles:
    active: local

--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: INFO

--- #test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
