spring:
  profiles:
    active: local


--- #test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          trace